runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /about
  script: about.php

- url: /dnc
  script: dnc.php

- url: /rnc
  script: rnc.php

- url: /undecided
  script: undecided.php

- url: /generate
  script: generate.php

- url: /
  script: index.html
