sed -i
 -e "s/president of the united states of america/President of the United States of America/g" \
 -e "s/united states of america/United States of America/g" \
 -e "s/united states congress/United States Congress/g" \
 -e "s/president barack obama/President Barack Obama/g" \
 -e "s/united states capitol/United States Capitol/g" \
 -e "s/vice president biden/Vice President Biden/g" \
 -e "s/united states senate/United States Senate/g" \
 -e "s/secretary of state/Secretary of State/g" \
 -e "s/planned parenthood/Planned Parenthood/g" \
 -e "s/independence hall/Independence Hall/g" \
 -e "s/governor o'malley/Governor O'malley/g" \
 -e "s/the liberty bell/the Liberty Bell/g" \
 -e "s/trump university/Trump University/g" \
 -e "s/elizabeth warren/Elizabeth Warren/g" \
 -e "s/african-american/African-American/g" \
 -e "s/the president's/the President's/g" \
 -e "s/president obama/President Obama/g" \
 -e "s/north carolina/North Carolina/g" \
 -e "s/know nothings/Know Nothings/g" \
 -e "s/latin america/Latin America/g" \
 -e "s/philadelphia/Philadelphia/g" \
 -e "s/constitution/Constitution/g" \
 -e "s/new hampshire/New Hampshire/g" \
 -e "s/rhode island/Rhode Island/g" \
 -e "s/bill clinton/Bill Clinton/g" \
 -e "s/new yorkers/New Yorkers/g" \
 -e "s/white house/White House/g" \
 -e "s/connecticut/Connecticut/g" \
 -e "s/trump tower/Trump Tower/g" \
 -e "s/mississippi/Mississippi/g" \
 -e "s/white house/White House/g" \
 -e "s/puerto rico/Puerto Rico/g" \
 -e "s/democratic/Democratic/g" \
 -e "s/republican/Republican/g" \
 -e "s/mike pence/Mike Pence/g" \
 -e "s/california/California/g" \
 -e "s/first lady/First Lady/g" \
 -e "s/mayflower/Mayflower/g" \
 -e "s/americans/Americans/g" \
 -e "s/democrats/Democrats/g" \
 -e "s/minnesota/Minnesota/g" \
 -e "s/tim kaine/Tim Kaine/g" \
 -e "s/september/September/" \
 -e "s/american/American/g" \
 -e "s/maryland/Maryland/g" \
 -e "s/november/November/g" \
 -e "s/congress/Congress/g" \
 -e "s/new york/New York/g" \
 -e "s/sanders/Sanders/g" \
 -e "s/clinton/Clinton/g" \
 -e "s/hillary/Hillary/g" \
 -e "s/america/America/g" \
 -e "s/indiana/Indiana/g" \
 -e "s/mexican/Mexican/g" \
 -e "s/montana/Montana/g" \
 -e "s/africa /Africa/g" \
 -e "s/rodham/Rodham/g" \
 -e "s/bernie/Bernie/g" \
 -e "s/muslim/Muslim/g" \
 -e "s/friday/Friday/g" \
 -e "s/oregon/Oregon/g" \
 -e "s/europe/Europe/g" \
 -e "s/mexico/Mexico/g" \
 -e "s/trump/Trump/g" \
 -e "s/lgbtq/LGBTQ/g" \
 -e "s/asia/Asia/g" \
 -e "s/god/God/g" \
 -e "s/u.s./US/g"
